# Generated by Django 4.2.6 on 2024-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('roll_no', models.CharField(max_length=15)),
                ('semester', models.IntegerField()),
                ('stream', models.CharField(max_length=40)),
                ('honor', models.CharField(max_length=10)),
                ('major', models.CharField(blank=True, max_length=30, null=True)),
                ('minor', models.CharField(blank=True, max_length=30, null=True)),
                ('exploratory', models.CharField(blank=True, max_length=30, null=True)),
                ('major_id', models.CharField(max_length=30)),
                ('minor_id', models.CharField(max_length=30)),
                ('exploratory_id', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=10)),
                ('course_duration', models.IntegerField()),
                ('contact_no', models.BigIntegerField()),
                ('personal_mail', models.EmailField(max_length=254)),
                ('parents_contact_no', models.BigIntegerField()),
                ('parents_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
