# Generated by Django 4.2.11 on 2024-04-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentsprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreStreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('stream', models.CharField(max_length=50)),
            ],
        ),
    ]
