# Generated by Django 4.2.6 on 2024-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDetailsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('sap_id', models.CharField(max_length=25)),
                ('question_number', models.IntegerField()),
                ('answer_key', models.CharField(max_length=100)),
                ('answer_marked', models.CharField(max_length=100)),
                ('your_time_taken', models.CharField(max_length=10)),
            ],
        ),
    ]
