# Generated by Django 4.2.6 on 2024-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_completioncertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionCertificates',
            fields=[
                ('uuid', models.UUIDField()),
                ('sap_id', models.CharField(max_length=20)),
                ('certificate_id', models.UUIDField(primary_key=True, serialize=False)),
                ('correctMarks', models.IntegerField()),
                ('TotalMarks', models.IntegerField()),
                ('completion_date', models.DateField()),
            ],
        ),
    ]
