# Generated by Django 4.2.11 on 2024-04-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('quiz_name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_id', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('backtracking', models.BooleanField(default=False)),
                ('upload', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('question_number', models.PositiveIntegerField()),
                ('question_description', models.TextField()),
                ('question_type', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(blank=True, max_length=255, null=True)),
                ('option4', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
