# Generated by Django 4.2.11 on 2024-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_quiz_details_quiz_question_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question_detail',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
